[project]
name = "auth"
version = "0.1.0"
description = "Authentication Service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "pwdlib[argon2]>=0.3.0",
    "pyjwt>=2.10.1",
]
